import type { Story } from "@/lib/types";

function article(
  partial: Story & { synopsis: string; description: string }
): Story {
  return partial;
}

/** Six in-depth sample articles for the News tab in dev/sample mode. */
export const SAMPLE_WORLD_NEWS: Story[] = [
  article({
    headline: "Global diplomacy stays focused on trade and security flashpoints",
    summary:
      "Major economies are recalibrating trade rules while security crises keep freight and deal timelines uncertain.",
    synopsis:
      "Governments on three continents tightened trade and security rules in the last 48 hours, and freight markets are already pricing in the friction.\n\nU.S. and EU officials opened new reviews of export controls on advanced chips, cloud services, and dual-use components, with compliance deadlines discussed for as early as 90 days out. Japan and South Korea held parallel consultations on supply-chain screening, while India signaled it may expand local-content requirements in government procurement worth an estimated $18B annually. None of these moves alone redraws global trade—but together they change paperwork, audit trails, and vendor lists for thousands of firms.\n\nMaritime insurers in the Red Sea corridor reportedly raised war-risk premiums 15–25% on select lanes after another week of disrupted transits. Shipowners diverted at least 12% of Asia–Europe container capacity around longer routes, adding 3–10 days to advertised transit times and $350–$900 per FEU in fuel and hire costs on some quotes. Three large manufacturers warned investors of $200M–$500M revenue exposure if disruptions run through Q3, and two auto suppliers flagged plant slowdowns tied to port queues in the mid-teens of hours.\n\nDiplomacy is active but inconclusive: four multilateral meetings are scheduled this week, yet no published tariff schedules or retaliatory lists have landed. Markets treated the week as a headline-risk event—transport equities whipsawed 1–3%—while credit desks widened spreads modestly on issuers with >40% revenue in affected corridors.\n\nWhat happens next: watch for any official export-control text, insurer renewals on July 1, and Fed or ECB speakers commenting on trade-sensitive growth forecasts. If new rules drop during earnings season, expect supply-chain commentary to dominate calls even when EPS beats consensus.",
    description:
      "The headline risk is cumulative. Export-control discussions often move markets before laws change: when semiconductors, cloud services, or dual-use components are involved, procurement teams rewrite vendor lists months ahead of formal rules. Security flashpoints amplify that friction—insurance repricing is a early indicator that boards take seriously because it hits P&L immediately, not eventually.\n\nFor multinational clients, the second-order effect is audit and documentation load. Trade counsel is asking for refreshed end-user certificates and country-of-origin trails on shorter cycles. Private equity portfolios with heavy industrial or consumer exposure are stress-testing EBITDA under scenarios where freight adds 80–120 bps to COGS for two quarters.\n\nWhat to watch next: whether any economy publishes retaliatory tariff schedules, and whether central banks in trade-heavy regions revise growth forecasts in upcoming speeches. If both happen in the same week, expect volatility in industrials and transport names even when earnings beats look solid.",
    whyItMatters:
      "If you serve multinational clients, managers will ask whether regional headlines are changing delivery, pricing, or compliance scope—having lane-level examples ready sounds prepared.",
    sourceUrl: "https://www.bbc.com/news/world",
    sourceName: "BBC World",
    imageUrl:
      "https://ichef.bbci.co.uk/ace/standard/480/cpsprodpb/3a6e/live/d52d0df0-6100-11f1-ae0d-afcc10479766.jpg",
  }),
  article({
    headline: "Energy and commodity prices still shape inflation narratives",
    summary:
      "Oil and gas benchmarks are volatile enough that CPI conversations at work are still tied to input costs, not just wages.",
    synopsis:
      "Energy and food commodities are still setting the tone for inflation talk—even when headline CPI looks calmer.\n\nBrent crude spent most of the week between $78 and $86 per barrel, a roughly 9% intra-month range that keeps transport and chemicals guidance volatile. U.S. Henry Hub natural gas jumped about 6% after storage prints came in below the five-year average, lifting utility input assumptions for July–August. European TTF gas moved in parallel, and two major trading houses flagged upside risk if summer heat beats forecasts by more than 1°C in key demand centers.\n\nAgricultural markets are split: wheat and corn contracts on some exchanges are up 3–4% month-to-date on Ukraine export corridor uncertainty and planting delays in parts of the U.S. Midwest, while soy and rice have been flatter as harvest estimates stabilized. Grocery CEOs in preview calls again cited promotional depth down 2–5% year-over-year and “shrinkflation” on package sizes—signals that consumers still trade down even where unemployment sits near 3.8–4.2% in major economies.\n\nCentral bankers used the data in speeches: two Fed officials and one ECB member said energy pass-through could keep policy “higher for longer” into late 2026, while a third argued goods disinflation will dominate. Bond markets priced roughly 8–12 bps of additional tightening risk over the next three meetings, though equities in consumer staples barely moved (<0.5%).\n\nFor the office: the debate is timing—commodity moves today often hit packaged-goods margins one to two quarters later. Next catalysts are OPEC+ guidance, U.S. CPI subcomponents for energy, and Q2 earnings from large retailers reporting gross-margin bridges.",
    description:
      "Energy is the bridge between geopolitics and earnings calls. When crude spikes even 8–10% inside a month, transport and chemicals margins compress quickly; when it fades, airlines and logistics names get relief—but labor contracts may still reset higher. That asymmetry is why CFOs keep fuel hedges and surcharge clauses on the agenda.\n\nFor office conversation, the useful frame is pass-through timing: retail and packaged goods companies often lag commodity moves by one to two quarters. That means today's commodity charts explain arguments you'll hear next quarter about margin guidance.\n\nNumbers to remember: mid-single-digit moves in gas can shift utility bills and fertilizer costs; for industrial clients, that shows up as working-capital swings more than dramatic revenue misses. Pair commodity direction with wage growth prints for a credible inflation take.",
    whyItMatters:
      "When someone says inflation is cooling, ask which input line item is still moving—energy, logistics, or labor—so you sound analytical, not argumentative.",
    sourceUrl: "https://www.reuters.com/world/",
    sourceName: "Reuters",
    imageUrl:
      "https://ichef.bbci.co.uk/ace/standard/480/cpsprodpb/590d/live/6821ba00-60f9-11f1-8b8c-6d33e1d5abb6.jpg",
  }),
  article({
    headline: "Election-year policy signals ripple through regulated industries",
    summary:
      "Campaign platforms are previewing tax and subsidy changes that could alter utilities, healthcare, and defense contractors.",
    synopsis:
      "Election-year policy leaks are moving sector models before any votes are cast.\n\nDraft proposals in Washington and Brussels would reshape manufacturing tax credits, with bonus rates discussed between 5 and 12 percentage points depending on whether plants land in designated zones. Lobbyists for autos, chips, and clean tech circulated scorecards showing NPV swings of $40M–$250M on hypothetical 500-worker facilities—numbers boards are already asking strategy teams to validate.\n\nHealthcare faces a parallel fight: industry groups estimate a 2-point shift in Medicare Advantage reimbursement formulas could move $8B–$12B annually across hospital systems and insurers, with rural networks cited as disproportionately exposed. Managed-care stocks swung 0.7–1.4% on the leak day, while facility operators with >60% government payor mix saw sharper moves.\n\nDefense markers slipped: preliminary budget language points to flat to +3% real growth versus earlier +5% plans, implying slower hiring at major primes and pressure on subcontractor margins. Foreign-policy aides tied the shift to supplemental spending debates worth roughly $14B still unresolved in committee.\n\nCredit markets noticed: mid-cap issuers with >30% revenue from regulated or subsidized lines saw spreads widen 15–25 bps, even as broad IG indices were flat. Equity reaction was muted overall—sector ETFs moved 0.4–1.1%—but options markets priced higher volatility into the next 45 days of primaries.\n\nNext on the calendar: committee markups in three key districts, a major candidate economic speech, and earnings from two hospital chains that typically guide Medicaid mix. If platforms converge, expect capex pull-forwards in manufacturing; if they diverge, disclosure footnotes on policy risk will multiply.",
    description:
      "Election cycles create narrative volatility before they create law. Investors trade on expected winners: clean energy, domestic chips, managed care, infrastructure suppliers. The mistake is treating every speech as settled policy; the opportunity is tracking which sectors have the highest beta to platform shifts.\n\nFor interns in audit or advisory, the practical angle is disclosure risk—clients may accelerate transactions or delay capex to optimize against uncertain tax treatment. You might hear questions about transfer pricing, R&D capitalization, or grant compliance as teams rehearse scenarios.\n\nWatch the calendar of committee hearings and primary results in swing regions with heavy manufacturing employment; those dates often precede sector rotations more than national polling averages do.",
    whyItMatters:
      "Clients in regulated industries will reference policy uncertainty in Q&A—connecting a headline to a balance-sheet line (capex, credits, reimbursement) is a strong intern move.",
    sourceUrl: "https://www.theguardian.com/world/rss",
    sourceName: "Guardian World",
  }),
  article({
    headline: "Humanitarian and migration pressures strain border economies",
    summary:
      "Cross-border labor and remittance flows are in focus as cities report budget pressure on housing and services.",
    synopsis:
      "Migration and humanitarian strain are showing up in budgets, labor data, and bond outlooks—not just border headlines.\n\nAt least six U.S. states and two Canadian provinces revised fiscal 2026 estimates upward by 4–7% for shelter, health intake, and school services, collectively adding billions in unplanned operating pressure. One border city cited a 19% year-over-year increase in emergency housing nights; another reported Medicaid enrollment growth 3.2 points above the state average. Municipal analysts said rating outlooks are stable for now, but liquidity cushions in three counties fell below 90 days of expenses.\n\nRemittance corridors remain hot: Mexico, Philippines, and Central America routes posted 6–9% dollar growth year-over-year in April prints, propping consumption abroad while intensifying wage competition in U.S. agriculture, hospitality, and logistics. Large employers in those sectors reported vacancy rates 2–3 points above 2019 averages despite national unemployment near 3.8–4.1%. Hourly wage offers in job postings rose 4–6% in the last quarter for entry roles in Texas and California border metros.\n\nNGOs estimate a $1.2B funding gap for the two largest active crises, and UN appeals are only 38% met mid-year. Diplomats tied aid shortfalls to harder sanctions coalition-building in two ongoing conflicts.\n\nMarkets reaction was diffuse: municipal spreads moved 5–10 bps in affected counties; consumer names with heavy labor exposure underperformed staples by ~60 bps. No single equity story dominated—this is a slow grind into cost structures.\n\nWhat to watch: summer housing ordinances, federal reimbursement rules, and Q2 earnings from staffing firms. If vacancy rates stay elevated while CPI cools, wage stickiness becomes the office debate—not immigration politics.",
    description:
      "Migration stories are economic stories: they affect wages, municipal bonds, and sector labor costs. For consumer and services clients, staffing is often the margin lever—when vacancy rates stay elevated, wage growth can persist even if headline inflation falls.\n\nHumanitarian funding gaps matter for geopolitics because they influence alliance politics and sanctions coalitions. A credible office comment links local labor tightness to global aid shortfalls without taking partisan sides—ask how your client's hiring plan changed this quarter.\n\nIf you cover municipal or state exposure, watch bond outlook revisions in border regions; spreads can move before national elections dominate coverage.",
    whyItMatters:
      "Workforce and municipal budget stress show up in client hiring and cost discussions—this headline helps you ask specific questions about labor plans.",
    sourceUrl: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    sourceName: "NYT World",
  }),
  article({
    headline: "Cyberattacks on infrastructure raise resilience spending",
    summary:
      "Utilities and ports report incident response costs, pushing cybersecurity budgets up double digits at many firms.",
    synopsis:
      "Cyber incidents on physical infrastructure are forcing real money decisions this quarter—not theoretical risk reviews.\n\nThree confirmed intrusions hit logistics and energy networks in five days: one port authority reported 36 hours of degraded throughput and an estimated $40M in delayed cargo value; a regional utility restored SCADA visibility after 18 hours but kept voluntary conservation alerts for 200,000 customers; a freight railroad flagged manifest delays averaging 11 hours on one corridor. CISA released two advisories with patch deadlines inside 72 hours, and at least 40 operators reported applying emergency fixes over the weekend.\n\nInsurance markets responded immediately: brokers quoted cyber renewals for mid-market industrials up 18–30% year-over-year, with deductibles rising from $1M to $2.5M on common towers and sublimits tightening on business interruption. One underwriter withdrew capacity for port-adjacent exposures until third-party pen tests are refreshed.\n\nRegulators accelerated timelines: EU draft rules discussed fines from €10M up to 4% of global revenue for late incident disclosure, with a 24-hour notification standard for critical sectors. U.S. counterparts floated similar clocks in committee, and two senators asked SEC for faster 8-K cyber granularity.\n\nCorporate guidance followed: four public infrastructure-adjacent firms pre-announced +12–15% IT security capex for the next two quarters while holding overall opex flat—implying cuts elsewhere. Identity vendors and MSSPs saw inbound RFP volume up double digits week-on-week, per channel checks.\n\nNext catalysts: insurer renewal season on July 1, a congressional hearing with CEOs of two attacked operators, and earnings from a major logistics REIT that typically discloses business-interruption sensitivities. Expect SOC 2 and vendor-concentration questions on every audit planning call.",
    description:
      "Cyber is no longer an IT sidebar—it is an operational risk with P&L timing. Port delays show up in inventory days on hand; utility outages show up in manufacturing downtime minutes. Boards want playbooks, not posters.\n\nFor professional services clients, the work is controls testing, incident readiness, and capitalizing vs expensing security tooling. Expect questions about SOC reports, vendor concentration, and backup site capacity.\n\nThe policy angle accelerates spending: when fines scale with revenue, compliance projects get prioritized ahead of discretionary digital experiments. Tie this story to any client pushing zero-trust or identity upgrades this year.",
    whyItMatters:
      "Security spend is a board topic—asking how incidents changed 2026 budgets shows you read beyond the headline.",
    sourceUrl: "https://feeds.npr.org/1001/rss.xml",
    sourceName: "NPR News",
  }),
  article({
    headline: "Climate-linked disasters keep insurance markets tight",
    summary:
      "Reinsurers are repricing catastrophe risk, affecting mortgages, construction, and municipal planning coast to coast.",
    synopsis:
      "Catastrophe insurance repricing is hitting mortgages, construction timelines, and town budgets—not just coastal headlines.\n\nJune reinsurance renewals in North America and Europe reportedly cleared 8–14% higher on average, with Florida and Gulf coastal property lines up 20–35% in the worst zones. Two global reinsurers reduced aggregate capacity by roughly $800M, forcing primary carriers to shrink limits or exit zip codes. Insurers non-renewed an estimated 2–3% of high-risk homeowner policies in six counties, pushing owners into state-backed plans priced 20–40% above private rates from 2023.\n\nConstruction pipelines are stalling: three regional builders publicly delayed projects totaling $1.1B in value because bonding and hazard coverage could not be placed inside budget; one cited a 47-day slip on a 300-unit development. Lenders tightened requirements—two banks raised minimum hazard deductibles to $25,000 from $10,000 for new originations in designated flood zones.\n\nScientists updated loss models for recent river flooding to a $3B–$6B economic range, including uninsured small-business inventory. Governors requested federal aid packages between $120M and $450M for four states, while FEMA application counts rose 18% week-over-week.\n\nEquity impact was selective: homebuilders with Gulf exposure underperformed peers by 1.2% over five sessions; reinsurance brokers outperformed by 0.8%. Munis in heavily affected counties saw 6–12 bps spread moves despite stable ratings.\n\nWhat happens next: July 1 primary renewals for smaller carriers, hurricane season forecasts on June 15, and a congressional hearing on NFIP funding. If a named storm forms early, expect instant repricing in transport, utilities, and retail foot traffic models—not just insurance stocks.",
    description:
      "Insurance tightening is a slow-motion credit story. When property coverage retreats, home prices, construction starts, and tax bases can all shift—municipal analysts watch this before equity investors do. For real assets clients, delay costs compound: labor, materials, and permit clocks keep running even when policies are unresolved.\n\nClimate headlines also feed ESG disclosure debates. Even firms with modest direct catastrophe exposure face investor questions about supply-chain concentration in hazard zones.\n\nUseful office framing: separate acute disaster costs from structural repricing. Acute events move news cycles; repricing changes cap rates for years. Clients need both lenses when discussing expansion plans.",
    whyItMatters:
      "Real estate, construction, and public-sector clients feel insurance costs immediately—mentioning repricing ranges sounds informed.",
    sourceUrl: "https://www.apnews.com/apf-topnews?output=rss",
    sourceName: "AP Top News",
  }),
];
